# Generated by Django 5.1.1 on 2024-11-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Ph_no', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
