# Generated by Django 5.1.1 on 2024-11-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Area_Stalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Food_type', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ratings', models.FloatField(max_length=100)),
                ('opening_time', models.IntegerField()),
                ('closing_time', models.IntegerField()),
            ],
        ),
    ]
