# Generated by Django 5.1.1 on 2024-11-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Area_Stalls', '0002_foodstall'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='Contact_num',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='closing_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='opening_time',
            field=models.CharField(max_length=100),
        ),
    ]
