# Generated by Django 5.1.1 on 2024-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Area_Stalls', '0004_foodstall_stall_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
