# Generated by Django 5.1.1 on 2024-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Area_Stalls', '0006_remove_foodstall_username_foodstall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='Location',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
