# Generated by Django 5.1.1 on 2024-11-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Area_Stalls', '0009_alter_foodstall_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstall',
            name='Location',
            field=models.URLField(default='NIL', max_length=500),
        ),
    ]
